git:
  depth: 100

matrix:
  include:
    - os: linux
      dist: trusty
  fast_finish: true

env:
  global:
    - CC_ENV=travis-ci
    - CC_PASSWORD=manage123
    - CC_TAG=10.5.0.0

services:
  - docker

# before_install:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
#  - docker-compose run --rm init
#  - docker-compose down
#  - docker-compose up -d cc
#  - docker-compose run --rm init ant waitcc test -Dbuild.dir=/tmp/build
#  - docker-compose down

  - antcc/bootstrap/install.sh
  - . $HOME/.bash_profile	  
  - antcc boot -Daccept.license=true
  - antcc up test stopcc

cache:
  directories:	
    - $HOME/Downloads
